version: '3.8'

services:
  # SQL Database server
  mariadb:
    image: mariadb:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
    volumes:
      - ./data/mariadb:/var/lib/mysql
#   Make sure no other processes are using this port
#    expose:
#      - 3306
    ports:
      - 3306

  # Interface for mariadb
  phpmyadmin:
    depends_on:
      - mariadb
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_HOST=mariadb
      - PMA_PORT=3306
      - PMA_USER=root
      - PMA_PASSWORD=my-secret-pw
      - PMA_ARBITRARY=1
  # Nginx webserver
  nginx:
    image: nginx:latest
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./projects:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    links:
      - php-fpm
  # PHP fpm image
  php-fpm:
    # Used custom php image to install core extensions
    build: docker/php-fpm
    restart: always
    volumes:
      - ./projects:/var/www/html

